[package]
name = "mafia"
version = "0.1.0"
authors = ["ahouts <ahouts4@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
chrono = { version =  "0.4", features = ["serde"] }
im = { version = "13.0", features = ["serde"] }
